### ISSUE TITLE
Question Labels: Validation Logic

### ISSUE THREAD

**Issue by poing** [kaykyb/freelancer-hosted-projects#10]
In the contest description, I did mention a concern with validation around the question labels.  They should be *unique*, because the are used as column names in a generate table.  

Can you add the validation logic here?

<img width="505" alt="Screen Shot 2019-06-11 at 10 20 33" src="https://user-images.githubusercontent.com/11417007/59236803-b554d580-8c32-11e9-87ef-c9f731b5d5e6.png">

*You can also give the field default values, like `q1,q2,q3` etc...*

![Screenshot_2019-06-11 Invite](https://user-images.githubusercontent.com/11417007/59237003-7d01c700-8c33-11e9-8258-90b1ddcd05fa.png)

**Comment by kaykyb** [comment]
> Can you add the validation logic here?

Sure!

Also, I think the whole validation of inputs needs some improvements. I'll be working on it too.

**Comment by kaykyb** [comment]
Validation is now much faster and precise. The labels are also validated now.
