### ISSUE TITLE
A couple questions...

### ISSUE THREAD

**Issue by poing** [kaykyb/freelancer-hosted-projects#8]
These questions are **not** part of the contest, **do not** need to be implemented, and are for my information!  *Just want to know if there are any limitations.*

1. Could the form *-or-* questions section accept a `variable`, *let's say a user account setting*, to specify the number of *default* questions?  *Instead of just the two `2` you show now?*
1. There's a *separate* process which allows users to duplicate a `survey`.  Loading all the settings from a previously saved `survey`.  Would it be possible to represent the canvas from *saved* settings?

**Comment by poing** [comment]
### **GREAT CONTEST ENTRY**
Just so you understand the contest process, every *suitable* entry will be evaluated by my staff and some of our clients.  Helping to select the winning entry at the **end** of the contest period.

Thanks for quickly addressing the *little* changes.  I hope the staff and clients like your entry, *good luck*.

**Comment by kaykyb** [comment]
1. Yes, it is possible to set a default questions number. Questions are stored in a an array:

![image](https://user-images.githubusercontent.com/15058641/59207099-baefe400-8b7c-11e9-8c01-108b827ddef6.png)

To implement this function, we simply need to add more questions to the array and add the connection between them.

The connections between questions are handled in an another array:

![image](https://user-images.githubusercontent.com/15058641/59207220-07d3ba80-8b7d-11e9-98de-bd3ac7035030.png)

To implement the function, we simply connect the `entry` to `q1`, `q1-next` to `q2`, `q2-next ` to `q3`, `q3-next` to `q4` and so on... until `q[n]-next` to `exit` (hangup).

---

2. Yes, it is also possible. The survey properties are stored in an state, we just need to save/load the state to change the survey.

For existing surveys, that don't have the position settings, we can simply position the questions in function of their number, so question `n` would have an `x` position of like 264px * `n` + 24px, for example, and an `y` position of 96px.

The other properties are converted from and to your data format using a custom function. The only modification needed in the backend is to add a property to save the positions of questions on the diagram.

**Comment by kaykyb** [comment]
The `x1`, `x2`, `y1` and `y2` properties are automatically set by the diagram based on the position of the questions.

**Comment by kaykyb** [comment]
> The only modification needed in the backend is to add a property to save the positions of questions on the diagram.

Actually, you don't even need to save the position of the questions, you can simply position them based on their number. But it is something I recommend for a better user experience with the diagram.

**Comment by kaykyb** [comment]
I'm working on an in-app testing utility to demonstrate the requested functions.

**Comment by poing** [comment]
Thank you for the confirmations.  Just wanted to understand what would be required.

> I'm working on an in-app testing utility to demonstrate the requested functions.

Just want to point out, it's **not** part of the contest  **-and-** that showing the additional functionality *may* confuse the staff or clients who I ask to rate the contest entries.  *Best to leave it as-is.*

**Comment by kaykyb** [comment]
Closing the issue.
