### ISSUE TITLE
Not a File Drop

### ISSUE THREAD

**Issue by poing** [kaykyb/freelancer-hosted-projects#9]
My browser does not like it when I drag a drop files to the audio files block.  Can you do one of the following?

* Remove the background color?  *The color makes me think I can just drop the file there.*
* Allow files to be dropped there?

<img width="629" alt="Screen Shot 2019-06-11 at 10 10 18" src="https://user-images.githubusercontent.com/11417007/59236437-27c4b600-8c31-11e9-953d-8e0e55110a94.png">

---

### Ooops

I **have** does this a few times already.

<img width="942" alt="Screen Shot 2019-06-11 at 10 15 37" src="https://user-images.githubusercontent.com/11417007/59236606-fb5d6980-8c31-11e9-8986-ecbc2e220fe9.png">

**Comment by kaykyb** [comment]
Now the block is a drop area!

![image](https://user-images.githubusercontent.com/15058641/59290943-20f96b80-8c50-11e9-9176-0f37bedaa29e.png)
